### ISSUE TITLE
Policy.authorized? does not work in Phoenix channels

### ISSUE THREAD

**Issue by hasmanyguitars** [boydm/policy_wonk#10]
Since `authorized?` only accepts a `Plug.Conn`, we had to implement this as a workaround in our channel:

```  
 %Plug.Conn{assigns: socket.assigns} |> MyApp.Auth.Policies.authorized?(:some_permission)
```

Could we have `authorized?` accept a socket in addition to conn or is there another way to handle this scenario in channels?

**Comment by boydm** [comment]
I'll be taking a look at this soon
