### ISSUE TITLE
Question: use case for async loading of a resource?

### ISSUE THREAD

**Issue by thojanssens** [boydm/policy_wonk#13]
Out of curiosity, could you share a typical use case of the use of **asynchronous** resource loading?
(And maybe include such an example use case in the doc?)

**Comment by boydm** [comment]
The asynchronous case is when you know you have more than one resource to load that are not dependent on each other. In other words, loading any resource does not depend on any of the other resources being loaded first.

This could be multiple rows from a db, reading a camera, opening a file, whatever. The only thing that matters is that the load operations are not inter-dependent.

In that case, there is no reason to serialize the loads. You might as well spin up multiple short-lived processes to load all the resources at the same time and thus save some response time from your server.

Think of it this way, if you need to load two unrelated rows from a db, or different dbs... most of the time you are waiting for the load to complete is doing no work on the server. It is just waiting for a response from another machine. You will get better overall performance by getting those loads going simultaneously.

**Comment by thojanssens** [comment]
Thank you, I get it now. I thought that the assigns will be updated asynchronously haha. So I understand that it allows to load resources simultaneously/asynchronously, and once that all have been fetched, the assigns will be updated and program continues.
