### ISSUE TITLE
Elixir 1.3.x

### ISSUE THREAD

**Issue by vrosancic** [boydm/policy_wonk#5]
Hi,

I am interested in using your lib for authorization, but I am getting a warning that says: "the dependency :policy_wonk requires Elixir "~> 1.4" but you are running on v1.3.4". Is it necessary to have Elixir 1.4.x? If no, can you lower the elixir requirement in your mix.exs file?

Thanks,
Vlado

**Comment by boydm** [comment]
I don't remember why it requires 1.4. I'll take a look soonish.

The new version, which targets phoenix 1.3 umbrella apps, will definitely need Elixir 1.4...

**Comment by boydm** [comment]
May be a bit late for you... but this is fixed in Master. Soonish apparently took a while...

**Comment by boydm** [comment]
Published to hex as version 0.2.1
