### ISSUE TITLE
Question: Is this ABAC?

### ISSUE THREAD

**Issue by kokjinsam** [boydm/policy_wonk#6]
Hello, thank you for creating this library! 

I'm in the process of learning [Attribute-based Access Control](https://en.wikipedia.org/wiki/Attribute-based_access_control) (ABAC) and stumbled upon your package. It seems like you have some of the [XACML](https://en.wikipedia.org/wiki/XACML) components implemented. But I'm not too sure if I'm right.

**Comment by boydm** [comment]
Think of it more as a plug framework where you can write ABAC policies.

I like simplicity with flexibility. If you want to write a policy that simply checks the time of day - go ahead. Or one that checks a random number would work too (lets you in 1/3 of the time...). 

If you really want to take on the formality of XACML - go ahead. That would work in a policy too, but isn't necessary. Either way, policies should be very small and composable.

**Comment by kokjinsam** [comment]
Thank you for clarifying!
