### ISSUE TITLE
Dialyzer error

### ISSUE THREAD

**Issue by tielur** [boydm/policy_wonk#8]
I'm getting this error when I run dialyzer on my project:
```elixir
lib/joint_registry/auth/policies.ex:15:callback_arg_type_mismatch
The inferred type for the 1st argument is not a
supertype of the expected type for the policy/2 callback
in the PolicyWonk.Policy behaviour.

Success type:

  atom()
  | %{:current_user => %JointRegistry.UserAccounts.User{:permissions => _, _ => _}, _ => _}


Behaviour callback type:
%Plug.Conn{
  :adapter => {atom(), _},
  :assigns => %{atom() => _},
  :before_send => [
    (%Plug.Conn{
       :adapter => {_, _},
       :assigns => map(),
       :before_send => [(_ -> any())],
       _ => _
     } ->
       %Plug.Conn{
         :adapter => {_, _},
         :assigns => map(),
         :before_send => [(_ -> any())],
         _ => _
       })
  ],
  :body_params => %Plug.Conn.Unfetched{
    :aspect => atom(),
    binary() =>
      binary()
      | [binary() | [any()] | %{binary() => _}]
      | %{binary() => binary() | [any()] | %{binary() => _}}
  },
  :cookies => %Plug.Conn.Unfetched{:aspect => atom(), binary() => binary()},
  :halted => _,
  :host => binary(),
  :method => binary(),
  :owner => pid(),
  :params => %Plug.Conn.Unfetched{
    :aspect => atom(),
    binary() =>
      binary()
      | [binary() | [any()] | %{binary() => _}]
      | %{binary() => binary() | [any()] | %{binary() => _}}
  },
  :path_info => [binary()],
  :path_params => %{
    binary() =>
      binary()
      | [binary() | [any()] | %{binary() => _}]
      | %{binary() => binary() | [any()] | %{binary() => _}}
  },
  :peer =>
    {{byte(), byte(), byte(), byte()}
     | {char(), char(), char(), char(), char(), char(), char(), char()}, char()},
  :port => char(),
  :private => %{atom() => _},
  :query_params => %Plug.Conn.Unfetched{
    :aspect => atom(),
    binary() =>
      binary()
      | [binary() | [any()] | %{binary() => _}]
      | %{binary() => binary() | [any()] | %{binary() => _}}
  },
  :query_string => binary(),
  :remote_ip =>
    {byte(), byte(), byte(), byte()}
    | {char(), char(), char(), char(), char(), char(), char(), char()},
  :req_cookies => %Plug.Conn.Unfetched{:aspect => atom(), binary() => binary()},
  :req_headers => [{binary(), binary()}],
  :request_path => binary(),
  :resp_body =>
    nil
    | binary()
    | maybe_improper_list(
        binary() | maybe_improper_list(any(), binary() | []) | byte(),
        binary() | []
      ),
  :resp_cookies => %{binary() => %{}},
  :resp_headers => [{binary(), binary()}],
  :scheme => :http | :https,
  :script_name => [binary()],
  :secret_key_base => nil | binary(),
  :state => :chunked | :file | :sent | :set | :set_chunked | :set_file | :unset,
  :status => nil | non_neg_integer()
}
________________________________________________________________________________
```

`lib/joint_registry/auth/policies.ex:15` is this:
```elixir
def policy(conn, :manage_invite) do
  allowed?(conn.current_user, [:manage_invite, :manage_any_invite])
end
```

**Comment by boydm** [comment]
Thanks. I'll take a look.

May be a little while tho as this isn't a functionality issue and I (perhaps obviously) haven't run dializer on it yet. If you can narrow it down (or even fix it?) that would be awesome.

**Comment by tielur** [comment]
Yea I'm not entirely sure it's policy_wonk's issue, it could very well be my application as well. I'll look into it more and report back here.

**Comment by tielur** [comment]
@boydm Okay so I think I've narrowed it down. I believe it's due to an incorrect callback definition. I think it was just a typo when the docs were changed in this commit: https://github.com/boydm/policy_wonk/commit/b21fe1cb03bc2501aa502ff5b83b8d08315d46e9

The current type specs have the first argument passed to to the `policy` callback being a `Plug.Conn` but it should be just a map like it was before.
#### Current callback definition
https://github.com/boydm/policy_wonk/blob/fca5453aa6044f9d28e2c54b087504844e6ef206/lib/policy.ex#L252

The callback definition is stating that an entire `Plug.Conn` struct is being passed but actually just the assigns is being passed. As you can see in a few spots: 

https://github.com/boydm/policy_wonk/blob/fca5453aa6044f9d28e2c54b087504844e6ef206/lib/policy.ex#L362-L364
https://github.com/boydm/policy_wonk/blob/fca5453aa6044f9d28e2c54b087504844e6ef206/lib/policy.ex#L391-L393
https://github.com/boydm/policy_wonk/blob/fca5453aa6044f9d28e2c54b087504844e6ef206/lib/policy.ex#L416-L418


I can confirm that fixing the callback definition to be a `Map.t()` or even `map()` fixes this issue. I've opened a PR to help out. Let me know if this doesn't make sense.

It's probably a different discussion on if it should actually be the conn, but the previous functionality seems like it's always been the assigns.

The `Plug.Conn` is returned in the `policy_error` callback though, which makes sense because often you need to redirect or do something else with the `conn`. As demonstrated here:
https://github.com/boydm/policy_wonk/blob/fca5453aa6044f9d28e2c54b087504844e6ef206/lib/policy.ex#L369-L371
